### PR TITLE
Create folder inside system tmpdir when installing Cabal lib on v2

### PR DESCRIPTION
**Pull request by lukel97**
This fixes an issue (at least on macOS) where installation would fail
because `cabal v2-install ...` would try to access
`$TMPDIR/TemporaryItems`. This gave a permissions error, so this patch
uses `withSystemTempDirectory` to avoid it, similar to how the v1 lib
install works.

### CODE REVIEW

**Comment by lukel97** [comment]
Here is the error, (when running from HIE on macOS) https://gist.github.com/bubba/c423400647e368f9e52a6fe6231526d5

**Comment by DanielG** [comment]
I'm a bit confused why this would fix anything as `withSystemTempDirectory` just calls `getTemporaryDirectory` internally too.

**Comment by lukel97** [comment]
@DanielG I had to reread this again, I forgot why I made this and `withSystemTempDirectory` does indeed call `getTemporaryDirectory`
But `withSystemTempDirectory` creates a new directory inside the temporary directory with the correct permissions, whereas previously it was just installing cabal straight in $TMPDIR or whatever

**Comment by DanielG** [comment]
Looking at this again I'm not actually sure why I needed a tmpdir to run v2-install to begin with. v1 does just fine in the root directory. I think I'm just going to change it and see what breaks.

**Comment by lukel97** [comment]
I think v2-installs pick up the .cabal file of the directory and complain about dependencies etc. if you’re trying to install something globally? But check what happens anyway

**Comment by DanielG** [comment]
Well I hardly think there'd be a cabal file at `/` :) but cabal is actually smart enough to stop searching at the user's home directory normally. Just not sure it actuall detects the search starting above it.

Anyways this seems to work locally, must have been a workaround for an old cabal-install bug then.

**Comment by DanielG** [comment]
Go ahead and try https://github.com/DanielG/cabal-helper/tree/fix-v2-install-osx if you like.

**Pull request closed without merging**
