### PR TITLE
Support for ghc-8.10.1

### PR DESCRIPTION
**Pull request by jneira**
* To help adding support for it in hie
* It is buildable but i have to check the test suites (specially the related with ghc session)

### CODE REVIEW

**Comment by DanielG** [comment]
I added you as a collaborator, can you please push this into a branch so CI picks it up. I'm also adding the 8.10 CI image as we speak so you can iterate on that.

**Comment by DanielG** [comment]
Ok I pushed the 8.10.1 image, see [wip/ci branch](https://github.com/DanielG/cabal-helper/tree/wip/ci). Just rebase on that, push it into a branch and get it working :)

**Comment by jneira** [comment]
Ok i am gonna active the ci, the test suite already failed for me in my windows local.

**Comment by jneira** [comment]
I am running the test suite in gitlab and i am getting timeouts for all jobs but ghc-8.8 and check-upd,
so i am not sure how can make some progress: https://gitlab.com/jneira/cabal-helper/pipelines/139478231

Locally i am not sure how to get more details in logs about the failing test:
* compile-test fails cause it is using posix commands (i am rying to fix it)
* program-test fails with
```
Running 1 test suites...
Test suite programs-test: RUNNING...
programs-test.exe: tests\ProgramsTest.hs:(23,3)-(32,73): Non-exhaustive patterns in case

Test suite programs-test: FAIL
Test suite logged to:
D:\dev\ws\haskell\cabal-helper\dist-newstyle\build\x86_64-windows\ghc-8.6.5\cabal-helper-1.0.0.0\t\programs-test\test\cabal-helper-1.0.0.0-programs-test.log
```
(the log file is exactly equal to the output 😆 )
So the warning is making the test fail?

**Comment by DanielG** [comment]
Ah yes, you need to change the job timeout under `Settings > CI / CD > General pipelines > Timeout` if you want to use your own fork. Really if you just push into a branch on my (GH) repo instead of your fork it will just work ;)

I'm not sure what the situation is if you create a PR on gitlab, maybe it would also use the settings from my repo then..

**Comment by DanielG** [comment]
> Locally i am not sure how to get more details in logs about the failing test

the new-build option `--test-show-details=direct` is your friend there. Also add `CABAL_HELPER_DEBUG=1` or `=2` to the environment to get more log output. ~~You could also just open that log file it's mentioning in the output there.~~ Oh, now I get what log file you were talking about. Obviosly `getProgName` is including an `.exe` on windos (gah).

**Comment by jneira** [comment]
> Really if you just push into a branch on my (GH) repo instead of your fork it will just work ;)

oh ok, i forgot i can push branches in this repo.

> the new-build option --test-show-details=direct is your friend there. Also add CABAL_HELPER_DEBUG=1 or =2 to the environment to get more log output

👍

**Comment by jneira** [comment]
After increasing timeout all buids are green but ghc-8.10.
Hopefully it will be fixed with 1cae401: https://gitlab.com/jneira/cabal-helper/pipelines/139883806

**Comment by jneira** [comment]
@DanielG m[y gitlab build was succesfully](https://gitlab.com/jneira/cabal-helper/pipelines/139883806) with 1cae401, so maybe this could be merged?

**Comment by lukel97** [comment]
Tracking this for cabal-plan https://github.com/haskell-hvr/cabal-plan/pull/56

**Comment by DanielG** [comment]
@jneira alright, I squashed your commits and pused them to #106, I'll merge it as soon as CI is green again.

**Pull request closed without merging**
