### PR TITLE
Fix cabal projects using source-repository-package

### LINKED ISSUE #99: Error loading projects with `source-repository-package`
* If you add a `source-repository-package` stanza in a `cabal.project` of a simple project, the load in haskell-ide-engine fails with:
```
cd d:\dev\ws\haskell\cabal-test; cabal v2-build --with-ghc=D:\bin\stack\x86_64-windows\ghc-8.6.5\bin\ghc.exe --with-ghc-pkg=D:\bin\stack\x86_64-windows\ghc-8.6.5\bin\ghc-pkg.exe --with-haddock=D:\bin\stack\x86_64-windows\ghc-8.6.5\bin\haddock.exe --project-file=d:\dev\ws\haskell\cabal-test\cabal.project --builddir=d:\dev\ws\haskell\cabal-test\dist-newstyle --dry-run all
Build profile: -w ghc-8.6.5 -O1
In order, the following would be built (use -v for more details):
 - my-source-repository-package-1.0.0.0 (lib) (first run)
 - cabal-test-0.1.0.0 (lib) (configuration changed)
 - cabal-test-0.1.0.0 (exe:cabal-test) (configuration changed)
hie-wrapper: panic! planPackages.mkPackage: Got non-unpacked package src!
```
* The error is thrown here:
https://github.com/DanielG/cabal-helper/blob/c20981c0cf56d0a9d9fbfba9be961dbb4d5896c9/src/CabalHelper/Compiletime/Program/CabalInstall.hs#L279

The error message seems to be logical but i supposed the load of projects with `source-repository-package` would be supported.

Original hie issue: https://github.com/haskell/haskell-ide-engine/issues/1621

### PR DESCRIPTION
**Pull request by DanielG**
Apparently we can get source-repo-packages in plan.json even when filtering
for `"style": "local"`(`UnitTypeLocal`). It's possible the root cause here
is a cabal bug as source-repository-package should really be treated more
like a tarball than a local package. Regardless we simply filter units by
actually checking for `uPkgSrc=Just LocalUnpackedPackage` instead of
relying on "style".

This fixes #99

### CODE REVIEW

**Comment by jneira** [comment]
All builds but the one that uses ghc-8.8.3 are faling for `cabal-head`:
```
Cabal.cabal:3:27: error:
unexpected At most 9 numbers are allowed per version number part
    2 | name:          Cabal
    3 | version: 3.3.2020041429742
      |   
```
Mmm i guess head `Cabal.cabal` are only compatible with the parser of Cabal-3.0.0.0 or above. 🤔

**Comment by DanielG** [comment]
Yeah, the fix for that is on the wip/ci branch: 8c35c5b6cf8f490301b2bad7c0ea48a4de5e0635 I was hoping you'd pull that onto master via #102 so I didn't have to ;)

**Comment by jneira** [comment]
Oh, right, i'll take a look asap to the test suite

**Comment by DanielG** [comment]
Merged as 262231a8f28feb711a8b164c62d9b89bcc11df47

**Pull request closed without merging**
