### PR TITLE
Make it able to find executable on Windows

### PR DESCRIPTION
**Pull request by iquiw**
You may prefer CPP solution though.

### CODE REVIEW

**Comment by DanielG** [comment]
Ah, I totally forgot about that. You can just use Distribution.Simple.BuildPaths.exeExtension though.

**Comment by iquiw** [comment]
Nice! I thought there must be some function to do it, but could not find it.
I'll close this.

**Comment by DanielG** [comment]
Keep it open so I don't forget about it.

**Comment by iquiw** [comment]
I updated the commit.

**Comment by DanielG** [comment]
Cool, thanks. I'll do a bunch of merging and releasing this weekend so hang on til then :)

**Pull request merged**
