### PR TITLE
[WIP] Cabal new-build support

### PR DESCRIPTION
**Pull request by DanielG**
_This branch will be rebased frequently, so don't even try to base anything on it. Base work on master instead. If I haven't merged in a while just ping me._

I've taken the opportunity of adding new-build support to also move a bunch of logic from ghc-mod into cabal-helper because the required ammount of abstraction for new-build support makes it natural to have that code live here.

The new API
- (will) support all the caching logic that lived in ghc-mod until now, including re-configuring projects when required and
- provides a project abstraction allowing (semi)transparent support for all project types (new-build, old-build and Stack)

### CODE REVIEW

**Comment by DanielG** [comment]
@alanz reports: currently we try to stat() `setup-config` of components which
are disabled.

Reason: cabal's solver includes disabled components in the build plan if doing
so doesn't require any additional changes to the existing plan. Hence if, for
example, tests only require additional dependencies but these do not constrain
the versions of packages already solved for the test components also get
included in plan.json. The selection of which components to actually act upon
happens at a later stage, in `Cmd*.hs`, after plan.json is generated. (Thanks to
@hvr for clearing that up)

- [ ] ~~TODO: Add component field to plan.json communicating which `--enable-*`
  flag is needed to enable building a given component.~~
  EDIT: Turned out not to be necessary. `cabal` just builds a component when you mention it explicitly.

- [ ] ~~TODO: Figure out if using the component type (lib, exe, bench etc.) from
plan.json is enough to filter out components that should be disabled. (Note:
"component-name" has this info)~~
 EDIT: Turns out we don't need to know about that actually.

**Comment by DanielG** [comment]
Running `cabal new-build --only-configure` as we do when `setup-congig`s need
generating will only act upon components enabled by default and not these
additional components that get included in the build plan despite being
disabled.

Accordingly we have two use-cases that we need to enable by patching cabal:

1. Given a specific component/unit configure (i.e. generate setup-config) for
  only this component, even if this component is currently not enabled by
  default.

2. Given a build plan read from plan.json we need to answer the question which
  components' `setup-config`s are allowed to be missing because they are
  speculative components. Conversly which `setup-config`s will be generated when
  we call `new-build --only-configure`.

**Comment by DanielG** [comment]
Turns out 1. already works if you specify a disable'd component's target explicitly :D

**Comment by DanielG** [comment]
Patch for 2.: https://github.com/haskell/cabal/pull/5659/files

**Comment by alanz** [comment]
So future cabal is in hand, what about current?  Do that thing we discussed about looking at what is actually in the `dist-newstyle` directory?

**Comment by DanielG** [comment]
I don't recall what you mean. `plan.json` has a `cabal-install` version field though, so I was just going to have it complain if the version is too old. I think it's reasonable to ask users to upgrade since upgrading cabal is usually the most painless thing in a haskell dev env :)

**Comment by alanz** [comment]
@DanielG I recall from my testing of cabal-helper recently that the plan.json represents everything that *can* be configured for a given project, not everything that *is* configured.

So this causes problems when cabal-helper is looking for e.g. benchmark components when they are not configured, and not needed for the current activity.

And one possible solution is to use the `plan.json` as a template of *possible* configured components, but to check on the file system what actually ends up there, and trim the bits that have not come through.

Presumably there is some core that would always be present, such as the `lib` part, if it exists.

**Comment by DanielG** [comment]
Yes, that is the point of the patch for 2.)

**Comment by alanz** [comment]
So the plan is to wait for the next release of cabal? Which could be a long wait, if history is any guide.

**Comment by DanielG** [comment]
Some more TODOs from MuniHac:

- [x] TODO: Helper compilation optimization (for Nix) 
Add a builtin helper like cabal does with `act-as-setup` so we can shortcut the whole runtime compilation logic when the environment is actually sane.

- [x] TODO: cabal-install version handling
2.2.0.0 doesn't have src-dir in plan.json yet, we need at least 2.4! Add some version checking

**Comment by DanielG** [comment]
- [x] TODO: Fix `qeReadProcess` usages ignoring output
I think just ignoring the output of a process and not consuming it could cause deadlocks since the output is probably consumed lazily (using `unsafeInterleaveIO`). Replace this with a `rawSystem` type function.

- [ ] TODO: Fix non-wrapped process invocations
When removing the wrapper exe we forgot to also wrap all the `readProcess`/`callProcess` calls in something overridable in `QueryEnv` so output can be captured by API clients. Previously this would be handled by the `qeReadProcess` call starting the wrapper exe.

**Comment by DanielG** [comment]
- [x] TODO: Update docker images to `cabal-install-2.4.1.0` for `--only-configure`

**Comment by ulidtko** [comment]
Congrats, Daniel. I didn't review, but this is an impressive chunk of work! Glad it's done.

**Comment by DanielG** [comment]
Well this isn't really done, Github just decided that it is because I push stuff to master when CI is green. :)

**Pull request merged**
