### PR TITLE
Fix inverted Cabal2.0 version check; fix cabal-preprocessors test

### PR DESCRIPTION
**Pull request by ulidtko**
Testing CI. (#47)

### CODE REVIEW

**Comment by DanielG** [comment]
FYI GitLab CI has proper integration for Github repos now, the CI turnaround times should be a lot faster now. Sorry it took so long before.

**Comment by DanielG** [comment]
@ulidtko are you still interested in carrying out this change?

**Comment by ulidtko** [comment]
Hi @DanielG !

Yes I'd still want to get this fixed. Thanks for pinging.

From the build errors, I guess that the version check might not be needed at all.

It's amazing that Gitlab Pipelines are integrated properly now -- although I still don't get it, when do they trigger to build? :)

**Comment by alanz** [comment]
I just tried various combinations of using the `componentOutDir/componentBuildDir` and none of them allow all the tests to pass.

Some combos let the preprocessor test pass, but then other tests fail.

**Comment by DanielG** [comment]
The build runs when you push to any branch in this repo, if that's what you mean.

**Review by DanielG — APPROVED** [review]

**Pull request merged**
