### PR TITLE
Fix Cabal version selection for build-type:Custom

### PR DESCRIPTION
**Pull request by DanielG**
Previously we would pick up Stack's Cabal version with ghc-pkg on the
global package-db. This however ignores that Stack also supports custom
Setup.hs with the Cabal version from the snapshot instead.

In cabal v2-build we have a similar problem. We used to assume that
plan.json's cabal-lib-version is used uniformly across units but this is
similarly untrue.

To fix both of these we re-stage the cabal version query to after
reconfiguring a unit, then we can just lookup the Cabal version in
setup-config.

### CODE REVIEW

**Comment by fendor** [comment]
Might this fix https://github.com/haskell/haskell-ide-engine/issues/1568 ?

**Comment by DanielG** [comment]
Should do, yeah.

**Comment by DanielG** [comment]
Testing.

**Comment by DanielG** [comment]
Testing2

**Comment by DanielG** [comment]
Testing3

**Pull request merged**
