### PR TITLE
Get building with ghc-8.10

### PR DESCRIPTION
**Pull request by lukel97**

### CODE REVIEW

**Comment by lukel97** [comment]
Looks like some of this is already done in wip/ci

**Comment by jneira** [comment]
Hey, i think #102 already adds support for ghc-8.10, it includes wip/ci and gitlab jobs are green

**Comment by lukel97** [comment]
Whoops, I'm late to the party

**Comment by jneira** [comment]
@bubba feel free to review it, although i think it includes all changes from this

**Pull request closed without merging**
