### PR TITLE
Allow exceptions 0.9, 0.10

### PR DESCRIPTION
**Pull request by Cynede**
change exceptions limit from < 0.9 to < 0.11

### CODE REVIEW

**Comment by DanielG** [comment]
Is there any particular reason for this change?

**Comment by Cynede** [comment]
@DanielG yes, I'm not fully remember exactly but in my ecosystem either few packages needed newer `exceptions` or older `exceptions` (0.8) was not fine with other packages versions, all of released `cabal-helper` versions are also conflicting with other newer packages so I've decided to use `master` with this patch

**Comment by DanielG** [comment]
Is this for a distro package or what? I need some context here :)

We can also update the dependency versions on Hackage if it turns out old cabal-helper versions work with newer `exceptions` versions. Would that help you at all?

**Comment by Cynede** [comment]
@DanielG well, sort of, but distro package have the same problems as user global installation by hand, except those deps conflicts are more transparent for package manager than for cabal resolver.
another release on hackage will be useful because I'll be able to switch from live version of package

**Comment by DanielG** [comment]
Hmm looks like `exception` is a superfluous dependency, at least in master, so we can remove it completely.

**Comment by DanielG** [comment]
I've updated cabal-helper-0.8.0.2 on Hackage to revision-1 and removed the bounds on exceptions there. The next release will remove the package dependency completely.

**Pull request closed without merging**
