### PR TITLE
Make it possible to use `flags` query without setup-config.

### PR DESCRIPTION
**Pull request by arrowd**
I thought it would be nice to get a list of package flags before configuring it.

### CODE REVIEW

**Comment by DanielG** [comment]
I like the general idea here but doing this directly in the wrapper seems dangerous. Remember that the wrapper is linked with a random version of Cabal, not necessarily one that the user is expecting to use (i.e. what cabal-install is really linked against).

Now granted you're only reading the generic package description and that should be fairly stable now, I'd still sleep better if we moved this to the main executable.

Actually after looking at the code I think the `flags` command already has the behavior you want since I use `unsafeInterleaveIO` for reading `setup-config` so it won't actually get accessed unless another command needs it.

Now as for the library API, the way we do caching for queries doesn't allow us to preserve this lazy behavior of the executable, I think using some exotic continuation monad we might be able to do that while preserving the current API but that seems excessive. How about you leave the `flags` query as it is and just add a `quickFlags` (or something) that calls the executable directly? I like the fact that the current API only ever calls the executable once per query and I'd like to preserve that behavior if possible.

Do you have any specific use case in mind for this BTW?

**Comment by arrowd** [comment]
In my usecase i want to present user all flags that are available for configuration. In most cases the queried package wouldn't be configured yet, so i need to work without setup-config.

Lazy IO in `CabalHelper/Main.hs` doesn't help because `setup-config` is also read in the wrapper:

```
projdir:distdir:args' -> do
      cfgf <- canonicalizePath (distdir </> "setup-config")
      mhdr <- getCabalConfigHeader cfgf
```

and if it isn't present, the query fails.

So, how do i find the helper executable? `compileHelper` need stuff from setup-config. And what if it isn't compiled yet?

**Comment by DanielG** [comment]
Ah yes, to compile main we already need setup-config. Well I guess we'll just have to risk it then.

Do you need this released soon? I'd like to have the build green before doing a release but I don't really have time to look into the failures myself. Unless you want to look into those failures I'm going to merge and release this when I find the time.

**Comment by DanielG** [comment]
Oh and also mind linking me to the project/branch you're using this in? I like keeping tabs on where cabal-helper is used :)

**Comment by arrowd** [comment]
Nope, i'm not in hurry. This is what i'm working on: [a plugin for HIE to build and query stack/cabal projects](https://github.com/arrowd/haskell-ide-engine/).

**Comment by arrowd** [comment]
Can we finally have this get in?

**Comment by DanielG** [comment]
Sorry for forgetting about this! Looking at it again now I don't really understand why you want to do this in cabal-helper. Since the generic package description is stable anyways why not just read the flags using Cabal directly in your HIE plugin?

**Comment by arrowd** [comment]
> Since the generic package description is stable anyways why not just read the flags using Cabal directly in your HIE plugin?

You mean, parsing .cabal file into a generic description will always succeed, whatever library version would be used?

**Comment by DanielG** [comment]
I do think so, for the foreseeable future at least. Otherwise cabal wouldn't be able to bootstrap either since at the very least they need to read the `cabal-version` field.

**Comment by arrowd** [comment]
Well, then this request can indeed be discarded.

**Pull request closed without merging**
