### PR TITLE
Bump upper bounds on dependencies

### PR DESCRIPTION
**Pull request by svmhdvn**
Also removes the dependency on semigroups since it has been added to base as of 4.9.0.0 and this package dependends on base >= 4.9.1.0. This change allows nixpkgs to remove a dependency override on this package's build.

### CODE REVIEW

**Comment by DanielG** [comment]
Thanks!

**Comment by DanielG** [comment]
Oh, do you need these to be applied on hackage too?

**Comment by svmhdvn** [comment]
Yes, I think all you’d need is a metadata update.

**Comment by DanielG** [comment]
There you go: https://hackage.haskell.org/package/cabal-helper-1.1.0.0/revisions/

I couldn't remove the semigroups dependency though since that's not allowed for revisions.

**Pull request merged**
